export const EXPERIENCES = [
  {
    title: 'Full Stack React Developer',
    description: `Developed and maintained multiple responsive web applications using React.js with TypeScript for the frontend and Node.js for the backend. Implemented GraphQL APIs to optimize data fetching and improve performance. Collaborated with cross-functional teams to design scalable architectures, integrate third-party services, and ensure smooth deployment across multiple projects.`,
    date: 'Feb 2024 - Present',
    company: 'IFCA Indonesia 365'
  },
  {
    title: 'Frontend Developer Freelancer',
    description: `Slicing and convert design to a React.js or Next.js source code, Create open source projects for people to use.`,
    date: 'Des 2023 - Feb 2024',
    company: ''
  },
  {
    title: 'After Sales & PPIC',
    description: `Forecasting spare part for aftersales needs, cost calculation to estimate profit/loss every project`,
    date: 'Mar 2020 - Nov 2023',
    company: 'Kikijaya Airconindo'
  },
  {
    title: 'Logistic Operator',
    description: `Responsible for part received not in defect, shortage, miss-part, or mix-part conditions Responsible to keeping stock ready for production and delivery need`,
    date: 'Jan 2018 - Feb 2020',
    company: 'Sugity Creatives'
  },
]

export const SKILLS = [
  "JavaScript",
  "TypeScript",
  "React.js",
  "Next.js",
  "Node.js",
  "express",
  "Azure DevOps",
  "Azure AD",
  "Docker",
  "PostgreSQL",
  "MySQL",
  "GraphQL",
  "REST API"
  "TailwindCSS",
  "SCSS",
  "Bootstrap",
  "Redux Toolkit",
  "Framer Motion",
  "Git",
  "HTML5",
  "CSS",
];

export const PROJECTS = [
  {
    id: 1,
    link: "https://absence-five.vercel.app/",
    img: "/projJfest1.png",
    img2: "/projJfest2.png",
    img3: "/projJfest3.png",
    name: "IFCAbsence | Absence System",
    desc: "This system automates attendance tracking by using facial recognition technology. It captures an image of each person’s face, identifies them using a trained database, and records their attendance automatically. This reduces manual errors, saves time, and ensures accurate and secure attendance management.",
    framework: "Next.js, React, Tailwind, Redux, ",
    demo: "https://absence-five.vercel.app/",
    src: "https://github.com/rizeenf/absence",
    color: "from-blue-50 to-orange-50",
  },
  {
    id: 2,
    link: "https://martabak-madness.vercel.app/",
    img: "/projChatapp2.png",
    img2: "/projChatapp2.png",
    img3: "/projChatapp2.png",
    name: "MartabakMadness | Food Delivery Apps",
    desc: "A convenient app that lets users instantly order their favorite meals from nearby restaurants. Users can quickly sign in using their Google account and enjoy fast, hassle-free food delivery.",
    framework: "React, Tailwind, Supabase Auth, Stripe",
    demo: "https://martabak-madness.vercel.app/",
    src: "https://github.com/rizeenf/martabak-madness",
    color: "from-orange-50 to-violet-50",
  },
  {
    id: 3,
    link: "myjfest.up.railway.app",
    img: "/projJfest1.png",
    img2: "/projJfest2.png",
    img3: "/projJfest3.png",
    name: "MyJfest | Ditigal Marketplace",
    desc: "MyJFest is a marketplace platform created for searching any Japanese events, we can see event details and buy event ticket if exist, it also build for Costume-maker sell their products in this platform.",
    framework: "Next.js, React, Tailwind, Redux, Stripe",
    demo: "http://myjfest.up.railway.app/",
    src: "https://github.com/rizeenf/jfest",
    color: "from-blue-50 to-orange-50",
  },
  {
    id: 4,
    link: "rize-chatreact-firebase.vercel.app",
    img: "/projChatapp2.png",
    img2: "/projChatapp2.png",
    img3: "/projChatapp2.png",
    name: "MWatsapp | Chat Apps",
    desc: "Chat Application build for an online chatting application, it allows you to have a conversation in real time, it can also have a image sharing option. Build using React for UI and Firebase for handling Auth and Storage (Firestore)",
    framework: "React, Tailwind, Firebase Auth, Firestore",
    demo: "https://rize-chatreact-firebase.vercel.app/",
    src: "https://github.com/rizeenf/chat-react-firebase",
    color: "from-orange-50 to-violet-50",
  },
  {
    id: 5,
    link: "rize-socialmedia.vercel.app",
    img: "/projSocialmed2.jpeg",
    img2: "/projSocialmed2.jpeg",
    img3: "/projSocialmed2.jpeg",
    name: "Sipaling social | Socialmedia",
    desc: "Mini social media that you can upload, post, like, comment, and share such as usual social media",
    framework: "React, Tailwind",
    demo: "https://rize-socialmedia.vercel.app/",
    src: "https://github.com/rizeenf/socialmedia",
    color: "from-violet-50 to-red-50",
  },
  {
    id: 6,
    link: "https://zashboard.vercel.app",
    img: "/projZashboard2.png",
    img2: "/projZashboard2.png",
    img3: "/projZashboard2.png",
    name: "Zashboard | Admin dashboard",
    desc: "Zashboard build for manage administration tool design for simplify data management. It transforms complex reports into visually appealing charts and tables for efficiently managing lists of items. Build using Charts from recharts and Data Table from MaterialUI",
    framework: "React, Sass, MaterialUI, Recharts",
    demo: "https://zashboard.vercel.app",
    src: "https://github.com/rizeenf/admindashboard",
    color: "from-red-50 to-orange-50",
  },
];
